NAME = "TorChat"
VERSION_MAJOR = "0.9.9"
VERSION_SVN = 550
VERSION_REV = "17"
EXPERIMENTAL = False
            
VERSION = VERSION_MAJOR + "." + str(VERSION_SVN) + ".rev" + str(VERSION_REV)
VERSION_ONLY = VERSION